import Head from "next/head";
import Details from "../components/Pots/Details";
import BannerSlider from "../components/Slider/BannerSlider";

export default function Home() {
	return (
		<div className="">
			<Head>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
				<title>MetalMania</title>
			</Head>

			<BannerSlider />

			<Details />
		</div>
	);
}
